version: "3.0"
services:
  gstore:
    image: dbpedia/gstore
    environment: 
      VIRT_USER: "dba"
      VIRT_PASS: "everyoneknows"
      VIRT_URI: "http://virtuoso:8890"
    ports:
      - "127.0.0.1:3002:8080"
    volumes:
      - ./data/repo:/gstore/git
  virtuoso:
    image: "openlink/virtuoso-opensource-7"
    environment:
      DBA_PASSWORD: "everyoneknows"
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://localhost:3000"
    ports:
      - "127.0.0.1:3003:8890"
    volumes: 
      - ./data/virtuoso:/database
