INSERT IN GRAPH <http://localhost:3002/g/test/mappings-geo-coordinates-mappingbased-2018.09.12-dataid.jsonld> {
<http://localhost:3000/janfo/mappings/geo-coordinates-mappingbased/2018.09.12#geo-coordinates-mappingbased_lang=nl.ttl.bz2> <http://purl.org/dc/terms/conformsTo> "http://dataid.dbpedia.org/ns/core#" .
<http://localhost:3000/janfo/mappings/geo-coordinates-mappingbased/2018.09.12#geo-coordinates-mappingbased_lang=nl.ttl.bz2> <http://dataid.dbpedia.org/ns/core#sorted> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://localhost:3000/janfo/mappings/geo-coordinates-mappingbased/2018.09.12#geo-coordinates-mappingbased_lang=nl.ttl.bz2> <http://dataid.dbpedia.org/ns/core#sha256sum> "6890e47989091b58037e3fc31d23e03467f83259182fb84c03e4645c77ce6b47" .
<http://localhost:3000/janfo/mappings/geo-coordinates-mappingbased/2018.09.12#geo-coordinates-mappingbased_lang=nl.ttl.bz2> <http://www.w3.org/ns/dcat#mediaType> <http://dataid.dbpedia.org/ns/mt#ApplicationNTriples> .
<http://localhost:3000/janfo/mappings/geo-coordinates-mappingbased/2018.09.12#geo-coordinates-mappingbased_lang=nl.ttl.bz2> <http://www.w3.org/ns/dcat#downloadURL> <https://downloads.dbpedia.org/repo/lts/mappings/geo-coordinates-mappingbased/2018.09.12/geo-coordinates-mappingbased_lang=nl.ttl.bz2> .
<http://localhost:3000/janfo/mappings/geo-coordinates-mappingbased/2018.09.12#geo-coordinates-mappingbased_lang=nl.ttl.bz2> <http://purl.org/dc/terms/modified> "2019-02-06T06:53:34Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
<http://localhost:3000/janfo/mappings/geo-coordinates-mappingbased/2018.09.12#geo-coordinates-mappingbased_lang=nl.ttl.bz2> <http://dataid.dbpedia.org/ns/core#uncompressedByteSize> "4405176"^^<http://www.w3.org/2001/XMLSchema#decimal> .
<http://localhost:3000/janfo/mappings/geo-coordinates-mappingbased/2018.09.12#geo-coordinates-mappingbased_lang=nl.ttl.bz2> <http://dataid.dbpedia.org/ns/core#compression> "bzip2" .
}
