SELECT DISTINCT ?uri ?title ?abstract ?description ?issued ?content WHERE {
  GRAPH ?g { 
    ?uri a <https://databus.dbpedia.org/system/voc/Collection> .
    ?uri <http://purl.org/dc/terms/title> ?title .
    ?uri <http://purl.org/dc/terms/abstract> ?abstract .
    ?uri <http://purl.org/dc/terms/description> ?description .
    ?uri <http://purl.org/dc/terms/issued> ?issued .
    ?uri <https://databus.dbpedia.org/system/voc/content> ?content .
  }
}